 version: '3.8'

 services:
     db:
       image: postgres:latest
       environment:
         POSTGRES_USER: ${DB_USERNAME}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: chat
       ports:
         - "5434:5432"

     app:
       build:
         context: .
         dockerfile: Dockerfile
       environment:
         DB_USERNAME: ${DB_USERNAME}
         DB_PASSWORD: ${DB_PASSWORD}
       ports:
         - "8080:8080"
       depends_on:
          - postgres
         
# docker build -t ua/chat:latest .
# docker-compose up -d
# docker-compose up
# docker-compose down