# Def profile configuration

# Data source settings for H2
spring:
<<<<<<< HEAD
  profiles:
    active: prod
  datasource:
#    added for comfort testing
    url: jdbc:h2:./chat
    username: yaq
    password:

# flyway settings for H2
  flyway:
#    added for comfort testing
    url: jdbc:h2:./chat
    user: yaq
    password:

# JPA and Hibernate setup for H2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

# Server port
server:
  port: 9999  port: 9999
=======
    profiles:
        active: prod
    datasource:
#    added for comfort testing
        url: jdbc:h2:./chat
        username: yaq
        password:

# flyway settings for H2
    flyway:
#    added for comfort testing
        url: jdbc:h2:./chat
        user: yaq
        password:

# JPA and Hibernate setup for H2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: none

# Server port
server:
    port: 9999
>>>>>>> parent of 26ec5a3a (Merge pull request #15 from AlbinaK33/onboarding)
