# Prod profile configuration

# Data source settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

# flyway settings
flyway:
  url: jdbc:postgresql://localhost:5432/chat
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}

# JPA and Hibernate setup
jpa:
  database: POSTGRESQL
  show-sql: true
  hibernate:
    ddl-auto: update #NONE
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
#jackson:
 # timezone: UTC

# Server port
server:
  port: 9999

    #Swagger
    #springdoc:
    #swagger-ui:
    #disable-swagger-default-url: true
  #path: /swagger-ui.html
